/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BuildingRouteImport } from './routes/building'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PrinciplesRouteImport } from './routes/principles'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsWarrantRouteImport } from './routes/products.warrant'
import { Route as ProductsWarrantMcpRouteImport } from './routes/products.warrant-mcp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingRoute = BuildingRouteImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinciplesRoute = PrinciplesRouteImport.update({
  id: '/principles',
  path: '/principles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsWarrantRoute = ProductsWarrantRouteImport.update({
  id: '/products/warrant',
  path: '/products/warrant',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsWarrantMcpRoute = ProductsWarrantMcpRouteImport.update({
  id: '/products/warrant-mcp',
  path: '/products/warrant-mcp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/building': typeof BuildingRoute
  '/platform': typeof PlatformRoute
  '/principles': typeof PrinciplesRoute
  '/products/warrant': typeof ProductsWarrantRoute
  '/products/warrant-mcp': typeof ProductsWarrantMcpRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/building': typeof BuildingRoute
  '/platform': typeof PlatformRoute
  '/principles': typeof PrinciplesRoute
  '/products/warrant': typeof ProductsWarrantRoute
  '/products/warrant-mcp': typeof ProductsWarrantMcpRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/building': typeof BuildingRoute
  '/platform': typeof PlatformRoute
  '/principles': typeof PrinciplesRoute
  '/products/warrant': typeof ProductsWarrantRoute
  '/products/warrant-mcp': typeof ProductsWarrantMcpRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/building'
    | '/platform'
    | '/principles'
    | '/products/warrant'
    | '/products/warrant-mcp'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/building'
    | '/platform'
    | '/principles'
    | '/products/warrant'
    | '/products/warrant-mcp'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/building'
    | '/platform'
    | '/principles'
    | '/products/warrant'
    | '/products/warrant-mcp'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuildingRoute: typeof BuildingRoute
  PlatformRoute: typeof PlatformRoute
  PrinciplesRoute: typeof PrinciplesRoute
  ProductsWarrantRoute: typeof ProductsWarrantRoute
  ProductsWarrantMcpRoute: typeof ProductsWarrantMcpRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building': {
      id: '/building'
      path: '/building'
      fullPath: '/building'
      preLoaderRoute: typeof BuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principles': {
      id: '/principles'
      path: '/principles'
      fullPath: '/principles'
      preLoaderRoute: typeof PrinciplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/warrant': {
      id: '/products/warrant'
      path: '/products/warrant'
      fullPath: '/products/warrant'
      preLoaderRoute: typeof ProductsWarrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/warrant-mcp': {
      id: '/products/warrant-mcp'
      path: '/products/warrant-mcp'
      fullPath: '/products/warrant-mcp'
      preLoaderRoute: typeof ProductsWarrantMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuildingRoute: BuildingRoute,
  PlatformRoute: PlatformRoute,
  PrinciplesRoute: PrinciplesRoute,
  ProductsWarrantRoute: ProductsWarrantRoute,
  ProductsWarrantMcpRoute: ProductsWarrantMcpRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
